### ISSUE TITLE
Изи гайд

### ISSUE THREAD

**Issue by ahydrax** [0exp/gem_template#1]
все понел

**Comment by 0exp** [comment]
Обана, KNFA Team

**Comment by 0exp** [comment]
С новым годом, пацаны, Титюха Тоха и все все все

**Comment by ahydrax** [comment]
по-братски спс, с нг, Рус

**Comment by 7dr1v3** [comment]
с новым годом руст!

**Comment by 0exp** [comment]
@7dr1v3 Стас, с наступившим тебя!

**Comment by 0exp** [comment]
Спасибо всем пацанам за движ

**Comment by akxcv** [comment]
ого
